import React from "react";
import {
  AbsoluteFill,
  spring,
  interpolate,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import { COLORS } from "../../constants/colors";
import { FONTS } from "../../constants/fonts";
import { SPRING_SNAPPY } from "../../constants/timing";
import { ParticleVortex } from "../shared/ParticleVortex";
import { SlideHeader } from "../shared/SlideHeader";
import { LiquidGlassCard } from "../shared/LiquidGlassCard";
import { GrainOverlay } from "../shared/GrainOverlay";

const alerts = [
  {
    code: "D1 · Duplicate Invoice",
    risk: "HIGH RISK",
    color: "#C0392B",
    finding: "Vendor 'Radiology Dept' | €145 | 2026-02-03 — billed twice to the same insurer on the same date.",
    action: "Verify with vendor. Reject duplicate before payment to avoid insurer clawback.",
  },
  {
    code: "D2 · Upcoding",
    risk: "HIGH RISK",
    color: "#C0392B",
    finding: "Procedure billed at €806 against a maximum allowed rate of €620. Excess of €186 per invoice.",
    action: "Withhold payment. Request clinical justification. Risk of EOPYY audit flag.",
  },
  {
    code: "D4 · Phantom Billing",
    risk: "HIGH RISK",
    color: "#C0392B",
    finding: "Invoice raised for patient P047 on 2026-03-14, but no appointment record exists for that date.",
    action: "Verify patient was physically present. Do not submit to insurer without confirmation.",
  },
  {
    code: "D11 · Repeated Same-Day Procedure",
    risk: "MEDIUM RISK",
    color: "#D4A017",
    finding: "Same procedure billed 3 times on the same day for the same patient. May be legitimate.",
    action: "Verify clinical notes confirm multiple administrations before submitting to insurer.",
  },
];

export const DemoResultsScene: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  const closeSpring = spring({ frame, fps, delay: 130, config: { damping: 200 } });
  const closeOpacity = interpolate(closeSpring, [0, 1], [0, 1]);

  return (
    <AbsoluteFill
      style={{
        background: COLORS.ink,
        padding: "60px 90px",
        flexDirection: "column",
        justifyContent: "center",
      }}
    >
      <ParticleVortex
        colorA={COLORS.goldLt}
        colorB="#E0594A"
        focalX={50}
        focalY={18}
        maxRadius={30}
        count={60}
        speed={0.55}
        opacity={0.5}
      />
      <GrainOverlay opacity={0.04} />

      <SlideHeader
        label="Live Demo Results"
        labelColor="#E0594A"
        dark
        titleSize={56}
        marginBottom={28}
        title={<>What the output looks like</>}
        subtitle="Real alerts generated by the prototype — 506 invoices analysed"
      />

      {/* Alert cards — 2×2 grid */}
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "1fr 1fr",
          gap: 22,
          marginBottom: 24,
        }}
      >
        {alerts.map((a, i) => {
          const sp = spring({ frame, fps, delay: 30 + i * 16, config: SPRING_SNAPPY });
          const y = interpolate(sp, [0, 1], [40, 0]);
          const opacity = interpolate(sp, [0, 0.5], [0, 1], { extrapolateRight: "clamp" });
          return (
            <div key={a.code} style={{ transform: `translateY(${y}px)`, opacity }}>
              <LiquidGlassCard
                dark
                accentColor={a.color}
                style={{
                  borderLeft: `5px solid ${a.color}`,
                  borderRadius: "0 20px 20px 0",
                  padding: "22px 26px",
                  height: "100%",
                }}
              >
                <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 12 }}>
                  <span
                    style={{
                      fontFamily: FONTS.sans,
                      fontSize: 15,
                      fontWeight: 700,
                      color: COLORS.cream,
                      letterSpacing: "0.04em",
                    }}
                  >
                    {a.code}
                  </span>
                  <span
                    style={{
                      fontFamily: FONTS.sans,
                      fontSize: 11,
                      fontWeight: 700,
                      color: COLORS.white,
                      background: a.color,
                      padding: "3px 10px",
                      borderRadius: 100,
                      letterSpacing: "0.08em",
                    }}
                  >
                    {a.risk}
                  </span>
                </div>
                <p
                  style={{
                    fontFamily: FONTS.sans,
                    fontSize: 17,
                    color: `${COLORS.cream}B0`,
                    margin: "0 0 12px",
                    lineHeight: 1.45,
                    fontWeight: 300,
                  }}
                >
                  {a.finding}
                </p>
                <div
                  style={{
                    display: "flex",
                    gap: 8,
                    alignItems: "flex-start",
                    paddingTop: 10,
                    borderTop: `1px solid ${a.color}22`,
                  }}
                >
                  <span style={{ color: a.color, fontSize: 14, fontWeight: 700 }}>Action</span>
                  <span
                    style={{
                      fontFamily: FONTS.sans,
                      fontSize: 15,
                      color: `${COLORS.cream}80`,
                      lineHeight: 1.4,
                      fontWeight: 300,
                    }}
                  >
                    {a.action}
                  </span>
                </div>
              </LiquidGlassCard>
            </div>
          );
        })}
      </div>

      {/* Closing summary line */}
      <p
        style={{
          fontFamily: FONTS.sans,
          fontSize: 18,
          color: `${COLORS.cream}90`,
          margin: 0,
          textAlign: "center",
          fontWeight: 300,
          opacity: closeOpacity,
        }}
      >
        All 70 alerts available in the full Excel report ·{" "}
        <span style={{ color: "#E0594A", fontWeight: 600 }}>53 HIGH priority</span> ·{" "}
        <span style={{ color: "#D4A017", fontWeight: 600 }}>17 MEDIUM priority</span>
      </p>
    </AbsoluteFill>
  );
};
